"""empty message

Revision ID: c8e4af15bcc4
Revises: 4d80e2b018a7
Create Date: 2023-04-18 20:09:15.373498

"""
from alembic import op
import sqlalchemy as sa
from app.models import environment, SCHEMA

# revision identifiers, used by Alembic.
revision = 'c8e4af15bcc4'
down_revision = '4d80e2b018a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlists',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=90), nullable=False),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('trades',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('portfolio_id', sa.Integer(), nullable=False),
                    sa.Column('ticker', sa.String(length=90), nullable=False),
                    sa.Column('quantity', sa.Numeric(
                        asdecimal=False), nullable=False),
                    sa.Column('price', sa.Numeric(
                        asdecimal=False), nullable=False),
                    sa.Column('trade_type', sa.String(
                        length=90), nullable=False),
                    sa.Column('timestamp', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['portfolio_id'], ['portfolios.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('watchlist_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('watchlist_id', sa.Integer(), nullable=False),
                    sa.Column('ticker', sa.String(length=90), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['watchlist_id'], ['watchlists.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    if environment == "production":
        op.execute(f"ALTER TABLE watchlist_items SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE watchlists SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE trades SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_items')
    op.drop_table('trades')
    op.drop_table('watchlists')
    # ### end Alembic commands ###
